version: 2.1
workflows:
  version: 2
  build:
    jobs:
      - build

jobs:
  build:
    working_directory: ~/express-acl
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: npm run tests
          command: npm tests
